import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import SideNav from "./components/SideNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout wraps every page.
 *
 * - Provides a solid app background (`.app-background`) matching the Figma app shell.
 * - Renders a fixed TopBar, then offsets the page content with top padding (`pt-24`)
 *   so content never appears beneath the fixed bar.
 */
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-background">
          <TopBar />
          <SideNav />
          <div className="mx-auto flex min-h-dvh w-full max-w-6xl flex-col px-4 pt-24 sm:px-8">
            <div className="flex flex-1 flex-col py-8 sm:flex-row sm:gap-8">
              {/* Spacer column so content never sits under the fixed SideNav. */}
              <div className="hidden w-[88px] shrink-0 sm:block" />
              <div className="flex flex-1 items-center justify-center">
                {children}
              </div>
            </div>
          </div>
          {modal}
        </div>
      </body>
    </html>
  );
}
